version: '3.3'

services:
  mongodb:
    ports:
      - '27017:27017'
    container_name: coffeeshop-mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=coffeeshop
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo:latest

  api:
    ports:
      - '8080:8080'
    container_name: coffeeshop-api
    image: coffeeshop-api:latest